import { writable } from 'svelte/store';

export type Language = 'en' | 'id';

const stored = typeof localStorage !== 'undefined' ? localStorage.getItem('jenderal_lang') as Language : null;
export const language = writable<Language>(stored || 'en');

language.subscribe(val => {
    if (typeof localStorage !== 'undefined') {
        localStorage.setItem('jenderal_lang', val);
    }
});

// Translation keys
const translations: Record<Language, Record<string, string>> = {
    en: {
        'nav.dashboard': 'Dashboard',
        'nav.guide': 'User Guide',
        'guide.contents': 'Contents',
        'guide.tip': 'Tip',
        'guide.warning': 'Warning',
        'nav.websites': 'Websites',
        'nav.server': 'Server',
        'nav.services': 'Services',
        'nav.nginx': 'Nginx',
        'nav.php': 'PHP',
        'nav.ssl': 'SSL Certificates',
        'nav.deploy': 'Deployments',
        'nav.cron': 'Cron Jobs',
        'nav.queue': 'Queue Workers',
        'nav.nodejs': 'Node.js',
        'nav.databases': 'Databases',
        'nav.docker': 'Docker',
        'nav.backups': 'Backups',
		'nav.security_center': 'Security Center',
        'nav.firewall': 'Firewall',
        'nav.processes': 'Processes',
        'nav.users': 'Users',
        'nav.alerts': 'Alerts',
        'nav.notifications': 'Notifications',
        'nav.terminal': 'Terminal',
        'nav.update': 'Update',
        'nav.audit': 'Audit Logs',
        'nav.settings': 'Settings',
        'nav.group.overview': 'Overview',
        'nav.group.web': 'Web & Apps',
        'nav.group.infrastructure': 'Infrastructure',
        'nav.group.security': 'Security',
        'nav.group.operations': 'Operations',
        'nav.group.system': 'System',
        'settings.language': 'Language',
        'settings.language.en': 'English',
        'settings.language.id': 'Bahasa Indonesia',
        'dash.title': 'Dashboard',
        'dash.welcome': 'Server overview',
        'dash.live': 'Live',
        'dash.reconnecting': 'Reconnecting…',
        'dash.refresh': 'Refresh',
        'dash.updated': 'Updated',
        'dash.resources': 'Resources',
        'dash.cpu': 'CPU',
        'dash.memory': 'Memory',
        'dash.disk': 'Disk',
        'dash.network': 'Network',
        'dash.swap': 'Swap',
        'dash.load': 'Load',
        'dash.download': 'Download',
        'dash.upload': 'Upload',
        'dash.history': 'Resource history',
        'dash.history.sub': 'Last 60 samples',
        'dash.no_history': 'Collecting samples…',
        'dash.system': 'System information',
        'dash.uptime': 'Uptime',
        'dash.uptime_since': 'up',
        'dash.quick': 'At a glance',
        'dash.websites': 'Websites',
        'dash.databases': 'Databases',
        'dash.backups': 'Backups',
        'dash.certificates': 'SSL Certs',
        'dash.alerts': 'Alerts',
        'dash.services': 'Services',
        'dash.services.running': 'running',
        'dash.services.stopped': 'stopped',
        'dash.services.all_ok': 'All services are running',
        'dash.ssl_attention': 'SSL needs attention',
        'dash.ssl_ok': 'All certificates are healthy',
        'dash.ssl.expires_in': 'expires in',
        'dash.ssl.expired': 'expired',
        'dash.ssl.days': 'days',
        'dash.recent_alerts': 'Recent alerts',
        'dash.alerts.none': 'No alerts. All metrics are normal.',
        'dash.alerts.resolved': 'resolved',
        'dash.error': 'Failed to load dashboard',
        'dash.retry': 'Try again',
        'dash.cores': 'cores',
        'dash.used': 'used',
        'dash.partitions': 'Partitions',
        'dash.manage': 'Manage',
        'dash.status.running': 'Running',
        'dash.status.stopped': 'Stopped',
        'dash.not_installed': 'not installed',
        'dash.active': 'active',
        'dash.alerts.unresolved': 'unresolved',
        'dash.ssl.need_attention': 'need attention',
    },
    id: {
        'nav.dashboard': 'Dasbor',
        'nav.guide': 'Panduan',
        'guide.contents': 'Daftar Isi',
        'guide.tip': 'Tips',
        'guide.warning': 'Perhatian',
        'nav.websites': 'Situs Web',
        'nav.server': 'Server',
        'nav.services': 'Layanan',
        'nav.nginx': 'Nginx',
        'nav.php': 'PHP',
        'nav.ssl': 'Sertifikat SSL',
        'nav.deploy': 'Deployment',
        'nav.cron': 'Tugas Cron',
        'nav.queue': 'Antrean Worker',
        'nav.nodejs': 'Node.js',
        'nav.databases': 'Database',
        'nav.docker': 'Docker',
        'nav.backups': 'Cadangan',
		'nav.security_center': 'Pusat Keamanan',
        'nav.firewall': 'Firewall',
        'nav.processes': 'Proses',
        'nav.users': 'Pengguna',
        'nav.alerts': 'Peringatan',
        'nav.notifications': 'Notifikasi',
        'nav.terminal': 'Terminal',
        'nav.update': 'Pembaruan',
        'nav.audit': 'Log Audit',
        'nav.settings': 'Pengaturan',
        'nav.group.overview': 'Ringkasan',
        'nav.group.web': 'Web & Aplikasi',
        'nav.group.infrastructure': 'Infrastruktur',
        'nav.group.security': 'Keamanan',
        'nav.group.operations': 'Operasi',
        'nav.group.system': 'Sistem',
        'settings.language': 'Bahasa',
        'settings.language.en': 'English',
        'settings.language.id': 'Bahasa Indonesia',
        'dash.title': 'Dasbor',
        'dash.welcome': 'Ringkasan server',
        'dash.live': 'Langsung',
        'dash.reconnecting': 'Menyambung ulang…',
        'dash.refresh': 'Muat ulang',
        'dash.updated': 'Diperbarui',
        'dash.resources': 'Sumber daya',
        'dash.cpu': 'CPU',
        'dash.memory': 'Memori',
        'dash.disk': 'Disk',
        'dash.network': 'Jaringan',
        'dash.swap': 'Swap',
        'dash.load': 'Beban',
        'dash.download': 'Unduh',
        'dash.upload': 'Unggah',
        'dash.history': 'Riwayat sumber daya',
        'dash.history.sub': '60 sampel terakhir',
        'dash.no_history': 'Mengumpulkan sampel…',
        'dash.system': 'Informasi sistem',
        'dash.uptime': 'Uptime',
        'dash.uptime_since': 'aktif',
        'dash.quick': 'Sekilas',
        'dash.websites': 'Situs Web',
        'dash.databases': 'Database',
        'dash.backups': 'Cadangan',
        'dash.certificates': 'Sertifikat SSL',
        'dash.alerts': 'Peringatan',
        'dash.services': 'Layanan',
        'dash.services.running': 'berjalan',
        'dash.services.stopped': 'berhenti',
        'dash.services.all_ok': 'Semua layanan berjalan',
        'dash.ssl_attention': 'SSL perlu perhatian',
        'dash.ssl_ok': 'Semua sertifikat sehat',
        'dash.ssl.expires_in': 'kedaluwarsa dalam',
        'dash.ssl.expired': 'kedaluwarsa',
        'dash.ssl.days': 'hari',
        'dash.recent_alerts': 'Peringatan terbaru',
        'dash.alerts.none': 'Tidak ada peringatan. Semua metrik normal.',
        'dash.alerts.resolved': 'pulih',
        'dash.error': 'Gagal memuat dasbor',
        'dash.retry': 'Coba lagi',
        'dash.cores': 'inti',
        'dash.used': 'terpakai',
        'dash.partitions': 'Partisi',
        'dash.manage': 'Kelola',
        'dash.status.running': 'Berjalan',
        'dash.status.stopped': 'Berhenti',
        'dash.not_installed': 'tidak terpasang',
        'dash.active': 'aktif',
        'dash.alerts.unresolved': 'belum pulih',
        'dash.ssl.need_attention': 'perlu perhatian',
    }
};

export function t(key: string): string {
    let lang: Language = 'en';
    language.subscribe(v => lang = v)();
    return translations[lang][key] || key;
}

// Reactive translation - use in components with $language
export function translate(lang: Language, key: string): string {
    return translations[lang]?.[key] || key;
}
