ALTER TABLE backups ADD COLUMN created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE backups ADD COLUMN task_id TEXT NOT NULL DEFAULT '';
ALTER TABLE backups ADD COLUMN kind TEXT NOT NULL DEFAULT 'manual';
ALTER TABLE backups ADD COLUMN started_at TEXT NOT NULL DEFAULT '';
ALTER TABLE backups ADD COLUMN finished_at TEXT NOT NULL DEFAULT '';
ALTER TABLE backup_schedules ADD COLUMN created_by TEXT NOT NULL DEFAULT '';
ALTER TABLE backup_schedules ADD COLUMN retention_keep INTEGER NOT NULL DEFAULT 0;
ALTER TABLE backup_schedules ADD COLUMN last_run_status TEXT NOT NULL DEFAULT '';
