ALTER TABLE websites ADD COLUMN octane_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE websites ADD COLUMN octane_port INTEGER NOT NULL DEFAULT 0;
ALTER TABLE websites ADD COLUMN octane_workers INTEGER NOT NULL DEFAULT 4;
