ALTER TABLE websites ADD COLUMN app_runtime TEXT NOT NULL DEFAULT '';
ALTER TABLE websites ADD COLUMN app_port INTEGER NOT NULL DEFAULT 0;
ALTER TABLE websites ADD COLUMN app_start_command TEXT NOT NULL DEFAULT '';
ALTER TABLE websites ADD COLUMN app_build_command TEXT NOT NULL DEFAULT '';
