ALTER TABLE websites ADD COLUMN proxy_scheme TEXT NOT NULL DEFAULT '';
ALTER TABLE websites ADD COLUMN proxy_host TEXT NOT NULL DEFAULT '';
ALTER TABLE websites ADD COLUMN proxy_port INTEGER NOT NULL DEFAULT 0;
